language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
  2.3.1
services:
  - postgresql
before_script:
  - psql -c 'create database scimitar_oryx_test;' -U postgres
  - bin/rake db:create db:schema:load 
